export const navLinks = [
  {
    title: "Home",
    link: "/",
    isButton: false,
    isLink: true,
    isNested: false,
    isExternal: false,
    isDisabled: false,
    hasIcon: false,
    icon: "",
    isAuth: false,
  },
  {
    title: "Contact",
    link: "/contact",
    isButton: false,
    isLink: true,
    isNested: false,
    isExternal: false,
    isDisabled: false,
    hasIcon: false,
    icon: "",
    isAuth: false,
  },
  {
    title: "About",
    link: "/About",
    isButton: false,
    isLink: true,
    isNested: false,
    isExternal: false,
    isDisabled: false,
    hasIcon: false,
    icon: "",
    isAuth: false,
  },
  {
    title: "Courses",
    link: "/courses",
    isButton: false,
    isLink: true,
    isNested: false,
    isExternal: false,
    isDisabled: false,
    hasIcon: false,
    icon: "",
    isAuth: false,
  },
];
