#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hook...🍺"

npm run lint || (
  echo "ESLint check failed. ❌ "
  exit 1
)
echo "ESLint check completed successfully. ✅ "

npm run prettier || (
  echo "Prettier check failed. ❌ "
  exit 1
)

echo "ESLint & Prettier check completed successfully. ✅ "

git add -A .

npm run build || (
  echo "Build failed. ❌ "
  exit 1
)
echo "Build completed successfully. ✅ "